    
	ghdl -a     riscv_decodeutil.vhd
	ghdl -a     lxp32_ram256x32.vhd
	ghdl -a     lxp32_mul16x16.vhd
	ghdl -a     lxp32_ubuf.vhd
	ghdl -a     lxp32_compl.vhd
	ghdl -a     riscv_interrupts.vhd
	ghdl -a     lxp32_scratchpad.vhd
	ghdl -a     riscv_regfile.vhd
	ghdl -a     lxp32_interrupt_mux.vhd
	ghdl -a     lxp32_shifter.vhd
	ghdl -a     lxp32_mul_dsp.vhd
	ghdl -a     lxp32_mul_opt.vhd
	ghdl -a     lxp32_mul_seq.vhd
	ghdl -a     lxp32_divider.vhd
	ghdl -a     riscv_mulsp6.vhd
	ghdl -a     lxp32_alu.vhd
	ghdl -a     lxp32_dbus.vhd
	ghdl -a     riscv_local_memmap.vhd
	ghdl -a     riscv_csr_unit.vhd
	ghdl -a     lxp32_fetch.vhd
	ghdl -a     riscv_decode.vhd
	ghdl -a     lxp32_decode.vhd
	ghdl -a     lxp32_execute.vhd
	ghdl -a     lxp32_cpu.vhd
	ghdl -a     lxp32u_top.vhd
	ghdl -a     bonfire_dm_icache.vhd
	ghdl -a     bonfire_cpu_top.vhd
	
