
  ghdl -a     ../bonfire-util/log2.vhd
  ghdl -a     ../bonfire-util/txt_util.vhd
  ghdl -a     rtl/riscv_decodeutil.vhd
  ghdl -a     rtl/csr_def.vhd
  ghdl -a     rtl/riscv_counter_64Bit.vhd
	ghdl -a     rtl/lxp32_ram256x32.vhd
	ghdl -a     rtl/lxp32_mul16x16.vhd
	ghdl -a     rtl/lxp32_ubuf.vhd
	ghdl -a     rtl/lxp32_compl.vhd
	ghdl -a     rtl/riscv_interrupts.vhd
	ghdl -a     rtl/lxp32_scratchpad.vhd
	ghdl -a     rtl/riscv_regfile.vhd
	ghdl -a     rtl/lxp32_interrupt_mux.vhd
	ghdl -a     rtl/lxp32_shifter.vhd
	ghdl -a     rtl/lxp32_mul_dsp.vhd
	ghdl -a     rtl/lxp32_mul_opt.vhd
	ghdl -a     rtl/lxp32_mul_seq.vhd
	ghdl -a     rtl/lxp32_divider.vhd
	ghdl -a     rtl/riscv_mulsp6.vhd
	ghdl -a     rtl/lxp32_alu.vhd
	ghdl -a     rtl/lxp32_dbus.vhd
	ghdl -a     rtl/riscv_local_memmap.vhd
	ghdl -a     rtl/riscv_csr_unit.vhd
	ghdl -a     rtl/lxp32_fetch.vhd
  ghdl -a     rtl/bonfire_fetch.vhd
	ghdl -a     rtl/riscv_decode.vhd
	ghdl -a     rtl/lxp32_decode.vhd
	ghdl -a     rtl/lxp32_execute.vhd
	ghdl -a     rtl/lxp32_cpu.vhd
	ghdl -a     rtl/lxp32u_top.vhd
	ghdl -a     rtl/bonfire_dm_icache.vhd
	ghdl -a     rtl/bonfire_cpu_top.vhd
